### PR TITLE
Adding string-to-integer-atoi for https://leetcode.com/problems/string-to-integer-atoi/

### PR DESCRIPTION
**Pull request by arjunrajpal**
Adding string-to-integer-atoi for https://leetcode.com/problems/string-to-integer-atoi/

### CODE REVIEW

**Comment by subhronilsaha** [comment]
I think it’ll be better to include the leetcode link in the file rather than in the commit message. Include the commented leetcode link at the very top of your file. 

Thanks.

**Comment by subhronilsaha** [comment]
Please do that for your other pull requests as well

**Comment by arjunrajpal** [comment]
Done for both @subhronilsaha, thanks !!

**Comment by subhronilsaha** [comment]
Looks good

**Pull request merged**
